-- USE 'hkbvtsjz9cohxt94' ;
USE cannahire;

INSERT INTO applicant_login
(first_name, last_name, email, resume, cover_letter, password)
VALUES ('Lauren', 'Santosuosso', 'noway@yahoo.com', 'resume here', 'Cover Letter would be put here', 'password');

INSERT INTO company_login
(company_name, company_website, company_email, password)  
VALUES ('Cresco Labs', 'www.crescolabs.com', 'hiring@crescolabs.com', 'password'),
('Noa Botanicals', 'www.noacares.com', 'hiring@noabotanicals.com', 'password'),
('Vangst Gigs', 'http://gigs.vangst.com', 'hiring@vangst.com', 'password'),
('Heally', 'www.healy.com', 'hiring@healy.com', 'password'),
('State of Utah', 'utah.gov', 'hiring@utah.gov', 'password'),
('Virtual Vocations', 'www.jobrapido.com', 'hiring@virtualvocations.com', 'password'),
('Truelieve', 'www.truelieve', 'hiring@truelieve.com', 'password'),
('Cura Cannabis Solutions', 'www.curacannabis.com', 'hiring@cura.com', 'password');

INSERT INTO job_postings
(job_title, company_name, city_state, job_description, employee_requirements)
VALUES ('Driver', 'Cresco Labs', 'Yellow Springs, Ohio', 'Full-Time Driver for our Yellow Springs Ohio facility', 'High School Diploma or Equivalent and a Valid Drivers License/Clean Driving Record, Must be 21 years old to apply'),
('Facility Maintenence Technician', 'Cresco Labs', 'Yellow Springs, Ohio', 'As the Facility Maintenance Technician, you will ensure the facility is maintained in a satisfactory condition for all required production and manufacturing operations.', 'The maintenance technician is responsible for the upkeep of the facility and should have a variety of skills, such as plumbing, electrical, carpentry and HVAC certification'),
('Lab Manufacturing Manager', 'Cresco Labs', 'Yellow Springs, Ohio', 'The Lab Manufacturing Manager will oversee and be responsible for all types of medicinal extracts from Cresco Labs product. The Lab Manufacturing Manager completes will maintain the organization, cleanliness and efficiency of production area.', 'To perform this job successfully, an individual should have proficiency with MS Office in a windows environment and familiar with sales tracking and reporting software'),
('QC Chemist', 'Cresco Labs', 'Yellow Springs, Ohio', 'The chemist will be responsible for testing equipment as well as assisting in the extraction process of medicinal cannabis. The chemist will test samples for identification, purity, and contaminants.', 'Bachelor’s Degree in chemistry or related field with 1-2 years HPLC experience'),
('Lab Manufacturing Technician', 'Cresco Labs', 'Yellow Springs, Ohio', 'Cresco Labs is seeking a Lab Manufacturing Technician to join our Yellow Springs, OH facility. The Lab Manufacturing Technician will be responsible for assisting in product processing and formulation', 'Two years of experience in a lab or manufacturing environment & Past experience in a highly regulated field producing pharmaceutical or nutraceutical products preferred'),
('Production Manager', 'Noa Botanicals', 'Honolulu, Hawaii', 'The Production Manager will lead and drive all aspects of Manoa Botanicals Production Facility processing of cannabis into safe, high quality, and effective cannabis products and successfully scale manufacturing.', 'Must be and remain compliant with any and all legal or company regulations for working in the cannabis industry. Bachelor’s degree in agriculture, manufacturing, or related field.'),
('Safety & Security Manager', 'Noa Botanicals', 'Honolulu, Hawaii', 'The Security and Safety Manager is responsible for day-to-day operations of Noa Botanicals security in accordance with state and local laws and standards set by the Organization.', 'Must be and remain compliant with all legal or company regulations for working in the cannabis industry. High School Diploma or GED Required'),
('Cannabis Support Staff', 'Noa Botanicals', 'Honolulu, Hawaii', 'Cannabis Support Staff provide on-site support for the trimming and packaging of Mānoa Botanicals LLC dba Noa Botanicals product. Cannabis Support Staff complete tasks assigned by the Team Lead to ensure the aesthetic appeal and high quality of product.', 'Previous experience in agriculture, trimming, or packaging preferred. High School Diploma or GED required. Minimum of 21 years of age as required by state statute.'),
('Human Resources Coordinator', 'Noa Botanicals', 'Honolulu, Hawaii', 'The Human Resources Coordinator works directly with and supports the Human Resources Director with recruiting and day-to-day HR functions and duties.', 'Bachelor’s degree in Human Resources or equivalent experience. Must pass all pre-employment reference and the background check requirements as required by state statute'),
('Product Specialist', 'Noa Botanicals', 'Honolulu, Hawaii', 'Product Specialist at Noa Botanicals is responsible for patient and caregiver intake, product transactions, and providing excellent customer service to a variety of audiences.', '2-3 years of previous sales experience preferred. Must be and remain compliant with any and all legal or company regulations for working in the cannabis industry.'),
('Grower-Cannabis', 'Vangst Gigs', 'Helena, Montana', 'Water plants following given SOP & Record all inputs to the room on a daily basis, calendar, and clipboard', 'Min 6+ months experience as a grower : personal experience OK but preferred if you have worked in a Grow and know the flexibility needed.' ),
('Support Representative(Remote Postion)', 'Heally', 'Bozeman, Montana', 'Work remotely from the comfort of your home. Sit in front of the computer and monitor different screens that show inbound questions and requests for our platform and respond to them.', 'High School Diploma or equivalent'),
('Cannabis Program Manager ', 'Utah Department of Agriculture and Food', 'Salt Lake City, Utah', 'Develop and implement procedures in response to agency policy, state, and federal laws, etc. Lay the foundation of and develop the state industrial hemp and medical cannabis programs.', 'A valid driver’s license.'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Salt Lake City, Utah', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Phoenix Arizona', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Mesa, Arizona', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Silver City, New Mexico', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Santa Fe, New Mexico', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Tulsa, Oklahoma', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Oklahoma City, Oklahoma', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'New Ulm, Minnesota', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Minneapolis, Minnesota', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Jefferson City, Missouri', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Kansas City, Missouri', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Little Rock, Arkansas', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Forrest City, Arkansas', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Lake Charles, Louisiana', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Baton Rouge, Louisiana', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Wheeling, West Virginia', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Charleston, West Virginia', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'Claremont, New Hampshire', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'concord, New Hampshire', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Brand Ambassador', 'Cura Cannabis Solutions', 'New York, New York', 'We are looking for an enthusiastic Brand Ambassador to promote and educate shops and patients about Select products.', 'All applicants must be over the age of 21 years to be eligible for employment at Cura'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Buffalo, New York', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Groton, Connecticut', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Rocky Hill, Connecticut', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Providence, Rhode Island', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Newport, Rhode Island', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Tenafly, New Jersey', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Jersey City, New Jersey', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Seaford, Delaware', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Dover, Delaware', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Cannabis Edibles Kitchen Lead', 'Truelieve', 'Baltimore, Maryland', 'This position exists to prep and cook cannabis-infused edible products within the kitchen in the production department.', 'Need to be able to cook well'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Bethesda, Maryland', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Pittsburgh, Pennsylvania', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Hershey, Pennsylvania', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Miami, Florida', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Palm Beach, Florida', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Valley City, North Dakota', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Watford, North Dakota', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Chicago, Illinois', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('Virtual Cannabis Industry Sales', 'Virtual Vocations', 'Peoria, Illinois', 'Individual must be able to fulfill the following responsibilities: Cold call leads to qualify and gauge interest', 'Excellent interpersonal written and verbal communication skills'),
('General Manager', 'Cura Cannabis Solutions', 'Spokane, Washington', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Cashmere, Washington', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Portland, Oregon', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Beaverton, Oregon', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Las Vegas, Nevada', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Reno, Nevada', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Carmel, California', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'San Francisco, California', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Anchorage, Alaska', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Fairbanks, Alaska', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Denver, Colorado', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Colorado Springs, Colorado', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Kennebunk, Maine', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Freeport, Maine', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Detroit, Michigan', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Ann Arbor, Michigan', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Granville, Vermont', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field'),
('General Manager', 'Cura Cannabis Solutions', 'Barre, Vermont', 'The General Manager will develop, build and maintain company strategic goals in line with Curas mission and values.', '5+ years of leadership experience in production, manufacturing management or a related field');





